export {default as Home} from './Home'
export {default as About} from './About'
export {default as Navbar} from './Navbar'
export {default as Features} from './Features'
export {default as Solutions} from './Solutions'
export {default as Supporting} from './Supporting'
export {default as FAQs} from './FAQs'
export {default as Footer} from './Footer'